/**
 * embed-data.ts — Reads website cache files and generates src/data.ts
 * Run via: npm run data (uses tsx)
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, join } from 'node:path'
import matter from 'gray-matter'

const ROOT = resolve(import.meta.dirname, '..', '..', '..')

const readJson = (relativePath: string) =>
  JSON.parse(readFileSync(join(ROOT, relativePath), 'utf-8'))

// GitHub data
const gh = readJson('public/static/data/github.json')
const profile = {
  login: gh.profile.login,
  name: gh.profile.name,
  publicRepos: gh.profile.public_repos,
  followers: gh.profile.followers,
  createdAt: gh.profile.created_at,
}
const contributionStats = gh.contributionStats
const languages = gh.languages.map((l: any) => ({
  name: l.name,
  percentage: l.percentage,
  color: l.color,
}))
const featured = gh.featured.map((f: any) => ({
  name: f.full_name,
  role: f.role,
  highlight: f.highlight,
  stars: f.stargazers_count,
  forks: f.forks_count,
  language: f.language,
}))

// Top repos (non-featured, sorted by stars)
const featuredNames = new Set(gh.featured.map((f: any) => f.full_name))
const topRepos = [...gh.repos, ...gh.repoPool]
  .filter((r: any) => !featuredNames.has(r.full_name))
  .sort((a: any, b: any) => b.stargazers_count - a.stargazers_count)
  .slice(0, 8)
  .map((r: any) => ({
    name: r.full_name,
    description: r.description || '',
    stars: r.stargazers_count,
    forks: r.forks_count,
    language: r.language,
    pushedAt: r.pushed_at,
  }))

// Recent activity (public events, last 5 groups)
const recentActivity = gh.recentActivity.groups
  .slice(0, 5)
  .map((g: any) => ({
    date: g.date,
    label: g.label,
    events: g.events
      .filter((e: any) => !e.isPrivate)
      .map((e: any) => ({
        kind: e.kind,
        repo: e.repo,
        message: e.message,
      })),
  }))
  .filter((g: any) => g.events.length > 0)

// Strava data
const strava = readJson('public/static/data/strava.json')
const cycling = {
  ...strava.rideStats,
  ytd: strava.ytdStats,
  categories: strava.rideCategories.map((c: any) => ({
    name: c.name,
    count: c.count,
    percentage: c.percentage,
    color: c.color,
  })),
  recentRides: strava.recentRides.slice(0, 5).map((r: any) => ({
    name: r.name,
    date: r.date,
    distance: r.distance,
    duration: r.duration,
    elevation: r.elevation,
    speed: r.speed,
    sportType: r.sportType,
  })),
}

// Author data
const authorMdx = readFileSync(join(ROOT, 'data/authors/default.mdx'), 'utf-8')
const { data: authorFm, content: authorBody } = matter(authorMdx)

// Site metadata
const siteMetaRaw = readFileSync(join(ROOT, 'data/siteMetadata.js'), 'utf-8')
const emailMatch = siteMetaRaw.match(/email:\s*['"]([^'"]+)['"]/)
const githubMatch = siteMetaRaw.match(/github:\s*['"]([^'"]+)['"]/)
const linkedinMatch = siteMetaRaw.match(/linkedin:\s*['"]([^'"]+)['"]/)
const siteUrlMatch = siteMetaRaw.match(/siteUrl:\s*['"]([^'"]+)['"]/)

// Blog posts
const blogDir = join(ROOT, 'data/blog')
const blogFiles = readdirSync(blogDir).filter((f) => f.endsWith('.mdx'))
const posts = blogFiles
  .map((file) => {
    const raw = readFileSync(join(blogDir, file), 'utf-8')
    const { data: fm, content: body } = matter(raw)
    return { fm, body }
  })
  .filter(({ fm }) => !fm.draft)
  .sort((a, b) => new Date(b.fm.date).getTime() - new Date(a.fm.date).getTime())
  .map(({ fm, body }) => ({
    title: fm.title,
    date: fm.date instanceof Date ? fm.date.toISOString().split('T')[0] : String(fm.date),
    tags: fm.tags || [],
    summary: fm.summary || '',
    body: body
      .trim()
      .replace(/<[A-Z][A-Za-z]*\s*\/>/g, '') // strip self-closing JSX components
      .replace(/<[A-Z][A-Za-z]*[^>]*>[\s\S]*?<\/[A-Z][A-Za-z]*>/g, '') // strip JSX blocks
      .trim(),
  }))

// Experience (import the TS file directly via tsx)
const { experience } = await import(join(ROOT, 'data/experience.ts'))
const { stats } = await import(join(ROOT, 'data/stats.ts'))

// Generate src/data.ts
const output = `// GENERATED by scripts/embed-data.ts — DO NOT EDIT
// Run \`npm run data\` to regenerate

export const profile = ${JSON.stringify(
  {
    name: authorFm.name,
    login: profile.login,
    occupation: authorFm.occupation,
    company: authorFm.company,
    companyUrl: authorFm.companyUrl,
    location: 'Winston-Salem, NC',
    bio: '15+ years building infrastructure for mission-driven organizations. Open source maintainer, nonprofit technologist, and full-stack engineer making the web work for people who are working to change it.',
    links: {
      site: siteUrlMatch?.[1] || 'https://kellymears.me',
      github: githubMatch?.[1] || authorFm.github,
      linkedin: linkedinMatch?.[1] || authorFm.linkedin,
      x: authorFm.twitter,
      email: emailMatch?.[1] || authorFm.email,
    },
  },
  null,
  2
)} as const

export const github = ${JSON.stringify(
  {
    repos: profile.publicRepos,
    followers: profile.followers,
    contributions: contributionStats.totalContributions,
    activeDays: contributionStats.activeDays,
    longestStreak: contributionStats.longestStreak,
    currentStreak: contributionStats.currentStreak,
    maxDay: contributionStats.maxDay,
    averagePerActiveDay: contributionStats.averagePerActiveDay,
    memberSince: new Date(profile.createdAt).getFullYear(),
    featured,
    topRepos,
    recentActivity,
    languages,
  },
  null,
  2
)} as const

export const cycling = ${JSON.stringify(cycling, null, 2)} as const

export const writing = ${JSON.stringify(posts, null, 2)} as const

export const experience = ${JSON.stringify(
  experience.map((e: any) => ({
    role: e.role,
    company: e.company,
    url: e.url,
    period: e.period,
    summary: e.summary,
    tags: e.tags,
    type: e.type,
  })),
  null,
  2
)} as const

export const stats = ${JSON.stringify(stats, null, 2)} as const
`

writeFileSync(join(ROOT, 'packages/cli/src/data.ts'), output, 'utf-8')
console.log('✓ Generated packages/cli/src/data.ts')
